### ISSUE TITLE
Start application instructions do not work

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix-Docs/StreamingAnalytics#1]
t_starter_app_deploy.md

Following the instructions to deploy the events application results in a crashed application. The instructions do not mention that you need to create a Streaming Analytics service and bind it to the application before starting it.

Also, it should use the `bx` cli to be consistent with other tutorials

**Comment by orzade** [comment]
Thanks for your comment. The topic has been adapted to comply more with tutorial requirements. This has fixed the first issue. Also, commands now use the bx cli: https://console.bluemix.net/docs/services/StreamingAnalytics/t_starter_app_deploy.html#starterapps_deploy
